KraftCinema/Models/Actor.cs
using System.ComponentModel.DataAnnotations;

namespace KraftCinema.Models
{
    public class Actor
    {
        public int? Id { get; set; }

        [Required]
        public string? Name { get; set; }

        public string? Gender { get; set; }

        public int? Age { get; set; }

        [Display(Name = "Profile")]
        public string? ActorLink { get; set; }

        [DataType(DataType.Upload)]
        public byte[]? Photo { get; set; }
    }
}

KraftCinema/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KraftCinema.Data;
using KraftCinema.Models;
using System.Text.Json;
using System.Web;
using System.Net;
using VaderSharp2;

namespace KraftCinema.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;

		public async Task<IActionResult> GetActorPhoto(int id)
		{
			var actor = await _context.Actor.FirstOrDefaultAsync(m => m.Id == id);

			if (actor == null)
			{
				return NotFound();
			}

			var imageData = actor.Photo;

			return File(imageData, "image/jpg");
		}

		public ActorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actor.ToListAsync());
        }

        public static async Task<List<string>> SearchRedditAsync(string searchQuery)
        {
            var returnList = new List<string>();
            var json = "";
            using (HttpClient client = new HttpClient())
            {
                //fake like you are a "real" web browser
                client.DefaultRequestHeaders.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
                json = await client.GetStringAsync("https://www.reddit.com/search.json?limit=100&q=" + HttpUtility.UrlEncode(searchQuery));
            }
            var textToExamine = new List<string>();
            JsonDocument doc = JsonDocument.Parse(json);
            // Navigate to the "data" object
            JsonElement dataElement = doc.RootElement.GetProperty("data");
            // Navigate to the "children" array
            JsonElement childrenElement = dataElement.GetProperty("children");
            foreach (JsonElement child in childrenElement.EnumerateArray())
            {
                if (child.TryGetProperty("data", out JsonElement data))
                {
                    if (data.TryGetProperty("selftext", out JsonElement selftext))
                    {
                        string selftextValue = selftext.GetString();
                        if (!string.IsNullOrEmpty(selftextValue)) { returnList.Add(selftextValue); }
                        else if (data.TryGetProperty("title", out JsonElement title)) //use title if text is empty
                        {
                            string titleValue = title.GetString();
                            if (!string.IsNullOrEmpty(titleValue)) { returnList.Add(titleValue); }
                        }
                    }
                }
            }
            return returnList;
        }
        public static string CategorizeSetiment(double sentiment)
        {
            if (sentiment >= -1 && sentiment < -0.6)
            {
                return "Extremely Negative";
            }
            else if (sentiment >= -0.6 && sentiment < -0.2)
            {
                return "Very Negative";
            }
            else if (sentiment >= -0.2 && sentiment < 0)
            {
                return "Slightly Negative";
            }
            else if (sentiment >= 0 && sentiment < 0.2)
            {
                return "Slightly Positive";
            }
            else if (sentiment >= 0.2 && sentiment < 0.6)
            {
                return "Very Positive";
            }
            else if (sentiment >= 0.6 && sentiment <= 1)
            {
                return "Extremely Positive";
            }
            else
            {
                return "Invalid sentiment Value";
            }
        }


        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            ActorDetailsVM aVM = new ActorDetailsVM();
            aVM.actor = actor;

            var movies = new List<Movie>();

            movies = await (from m in _context.Movie
                            join ma in _context.MovieActor on m.Id equals ma.MovieID
                            where ma.ActorID == id
                            select m).ToListAsync();
            aVM.movies = movies;

            var queryText = actor.Name;
            var json = "";

            using (WebClient wc = new WebClient())
            {
                //fake like you are a "real" web browser
                wc.Headers.Add("user-agent", "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; .NET CLR 1.0.3705;)");
                json = wc.DownloadString("https://www.reddit.com/search.json?limit=100&q=" + HttpUtility.UrlEncode(queryText));
            }

            List<string> textToExamine = await SearchRedditAsync(actor.Name);

            var analyzer = new SentimentIntensityAnalyzer();
            int validResults = 0;
            double resultsTotal = 0;
            List<string> web = new List<string>();
            foreach (string textValue in textToExamine)
            {
                var results = analyzer.PolarityScores(textValue.Substring(0, textValue.Length < 2500 ? textValue.Length : 2500));
                if (results.Compound != 0)
                {
                    resultsTotal += results.Compound;
                    validResults++;
                }
                web.Add(textValue.Substring(0, textValue.Length < 100 ? textValue.Length : 100));
            }

            double avgResult = Math.Round(resultsTotal / validResults, 2);
            aVM.rating = actor.Name + " " + avgResult.ToString() + ": " + CategorizeSetiment(avgResult);

            aVM.posts = web;

            return View(aVM);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,ActorLink")] Actor actor, IFormFile ActorPhoto)
		{
			ModelState.Remove(nameof(ActorPhoto));

			if (ModelState.IsValid)
			{
				if (ActorPhoto != null && ActorPhoto.Length != 0)
				{
					var memoryStream = new MemoryStream();
					await ActorPhoto.CopyToAsync(memoryStream);
					actor.Photo = memoryStream.ToArray();
				}
				else
				{
					actor.Photo = new byte[0];
				}
				_context.Add(actor);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(actor);
		}

		// GET: Actors/Edit/5
		public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int? id, [Bind("Id,Name,Gender,Age,ActorLink")] Actor actor, IFormFile ActorPhoto)
		{
			if (id != actor.Id)
			{
				return NotFound();
			}

			Actor existingActor = _context.Actor.AsNoTracking().FirstOrDefault(m => m.Id == id);

			if (ActorPhoto != null && ActorPhoto.Length != 0)
			{
				var memoryStream = new MemoryStream();
				await ActorPhoto.CopyToAsync(memoryStream);
				actor.Photo = memoryStream.ToArray();
			}

			else if (existingActor == null)
			{
				actor.Photo = existingActor.Photo;
			}
			else
			{
				actor.Photo = new byte[0];
			}
			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(actor);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!ActorExists(actor.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(actor);
		}

		// GET: Actors/Delete/5
		public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var actor = await _context.Actor.FindAsync(id);
            if (actor != null)
            {
                _context.Actor.Remove(actor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int? id)
        {
            return _context.Actor.Any(e => e.Id == id);
        }
    }
}

KraftCinema/Views/Actors/Create.cshtml
@model KraftCinema.Models.Actor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Actor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActorLink" class="control-label"></label>
                <input asp-for="ActorLink" class="form-control" />
                <span asp-validation-for="ActorLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input type="file" id="ActorPhoto" name="ActorPhoto" multiple class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

KraftCinema/Views/Actors/Delete.cshtml
@model KraftCinema.Models.Actor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Actor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ActorLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ActorLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

KraftCinema/Views/Actors/Details.cshtml
@model KraftCinema.Models.ActorDetailsVM

@{
	ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
	<h4>Actor</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.actor.Name)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.actor.Name)
		</dd>
		<dt class="col-sm-10">
			@if (Model.actor.Photo != null && Model.actor.Photo.Length != 0)
			{
				<img height="150" src="@Url.Action("GetActorPhoto", "Actors", new {Model.actor.Id})" />
			}
		</dt>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model?.actor.Id">Edit</a> |
	<a asp-action="Index">Back to List</a>
</div>

<h1>Reddit Analysis</h1>
<h4>@Html.DisplayFor(model => model.rating)</h4>
<table id="redditTable" class="table">
	<thead>
		<tr>
			<th>Reddit Posts</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model.posts)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item)
				</td>
			</tr>
		}
	</tbody>
</table>
@section Scripts {
	<link rel="stylesheet" href="https://cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" integrity="sha384-zUxWDVAcow8yNu+q4VFsyZA3qWsKKGdWPW0SVjaR12LQze4SY8Nr75US6VDhbWkf" crossorigin="anonymous">
	<script src="https://cdn.datatables.net/2.0.1/js/dataTables.min.js" integrity="sha384-O1CwIpQyArpIVIf/MmRsfivHkHhSlKgnk+wOxIMeEqObjH8MoV/Ox0ue6FlCwucf" crossorigin="anonymous"></script>
	<script>let table1 = new DataTable('#redditTable');</script>
}

KraftCinema/Views/Actors/Edit.cshtml
@model KraftCinema.Models.Actor

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Actor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ActorLink" class="control-label"></label>
                <input asp-for="ActorLink" class="form-control" />
                <span asp-validation-for="ActorLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input type="file" id="ActorPhoto" name="ActorPhoto" multiple class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

KraftCinema/Views/Actors/Index.cshtml
@model IEnumerable<KraftCinema.Models.Actor>

<h1>Index</h1>

<p>
	<a asp-action="Create">Create New</a>
</p>
<table id="indexTable" class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.Name)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Gender)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Age)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ActorLink)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Photo)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Gender)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Age)
				</td>
				<td>
					<a href="@Html.DisplayFor(modelItem => item.ActorLink)" target="_blank">IMDB</a>
				</td>
				<th>
					@if (item.Photo != null && item.Photo.Length != 0)
					{
						<img height="150" src="@Url.Action("GetActorPhoto", "Actors", new {item.Id})" />
					}
				</th>
				<td>
					<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
					<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
					<a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
				</td>
			</tr>
		}
	</tbody>
</table>

@section Scripts {
	<link rel="stylesheet" href="https://cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" integrity="sha384-zUxWDVAcow8yNu+q4VFsyZA3qWsKKGdWPW0SVjaR12LQze4SY8Nr75US6VDhbWkf" crossorigin="anonymous">
	<script src="https://cdn.datatables.net/2.0.1/js/dataTables.min.js" integrity="sha384-O1CwIpQyArpIVIf/MmRsfivHkHhSlKgnk+wOxIMeEqObjH8MoV/Ox0ue6FlCwucf" crossorigin="anonymous"></script>
	<script>let table = new DataTable('#indexTable');</script>
}